$activeBorderColor = rgb(ea5e79)

general {
    col.active_border = $activeBorderColor
}

decoration {
    rounding = 12
}

group {
    col.border_active = $activeBorderColor
}

group {
    col.border_active = $activeBorderColor
}
